

import { AppLoader } from "@/components/app-loader";
import { AuthInitializer } from "@/components/auth-initializer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const notoSansLao = localFont({
  src: "./fonts/NotoSansLao-Regular.ttf",
  variable: "--font-noto-lao",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="lo"
      className={`
        ${notoSansLao.variable}
        ${geistSans.variable}
        ${geistMono.variable}
      `}
    >
      <body className="font-lao antialiased">
        <Providers>
          <AuthInitializer />
          <AppLoader>
            {children}
          </AppLoader>
        </Providers>
      </body>
    </html>
  );
}