// import { AppLoader } from "@/components/app-loader";
// import { AuthInitializer } from "@/components/auth-initializer";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Providers } from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Providers>
//           <AuthInitializer />
//           <AppLoader>
//             {children}
//           </AppLoader>
//         </Providers>
//       </body>
//     </html>
//   );
// }



import { AppLoader } from "@/components/app-loader";
import { AuthInitializer } from "@/components/auth-initializer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"; // 1. Import localFont ເຂົ້າມາເພີ່ມ
import "./globals.css";
import { Providers } from "./providers";

// 2. ຕັ້ງຄ່າ Local Font ສຳລັບໄຟລ໌ notosanlao.ttf
const notoSanLao = localFont({
  src: "./fonts/NotoSansLao-Regular.ttf", // 💡 ກະລຸນາກວດສອບວ່າວາງໄຟລ໌ໄວ້ທີ່ໂຟນເດີ app/fonts/notosanlao.ttf ແລ້ວຫຼືບໍ່
  variable: "--font-noto-lao",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 3. ປ່ຽນ lang="en" ເປັນ lang="lo" ໃຫ້ເໝາະສົມກັບເວັບພາສາລາວ
    <html lang="lo" className={`${notoSanLao.variable}`}>
      {/* 4. ເອົາ Class "font-lao" ມາໃສ່ທີ່ <body> ເພື່ອໃຫ້ທັງເວັບໄຊທ໌ໃຊ້ຟອນທ໌ລາວນີ້ເປັນ Font ຫຼັກ (Default) */}
      <body className={`${geistSans.variable} ${geistMono.variable} font-lao antialiased`}>
        <Providers>
          <AuthInitializer />
          <AppLoader>
            {children}
          </AppLoader>
        </Providers>
      </body>
    </html>
  );
}
