import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import dayjs from "dayjs";
import { getPageCount } from "./pdfInternal";

// ================= TYPES =================

export type PDFType = "report" | "invoice" | "custom";

export type Column<T> = {
    header: string;
    key: keyof T | "__index";
};

export type ExportPDFParams<T extends Record<string, unknown>> = {
    type: PDFType;
    title: string;
    fileName?: string;
    columns: Column<T>[];
    data: T[];
    meta?: {
        companyName?: string;
        address?: string;
        phone?: string;
        email?: string;
    };
};

// jsPDF extension type (NO any)
type jsPDFWithAutoTable = jsPDF & {
    lastAutoTable?: {
        finalY: number;
    };
};

// ================= PDF ENGINE =================

export const exportPDF = <T extends Record<string, unknown>>(
    params: ExportPDFParams<T>
) => {
    const {
        type,
        title,
        fileName,
        columns,
        data,
        meta,
    } = params;

    // ✅ CREATE DOC FIRST
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    }) as jsPDFWithAutoTable;

    // ================= HEADER =================

    doc.setFontSize(18);
    doc.text(meta?.companyName ?? "My Company", 14, 18);

    doc.setFontSize(10);
    doc.text(meta?.address ?? "", 14, 24);
    doc.text(meta?.phone ?? "", 14, 28);
    doc.text(meta?.email ?? "", 14, 32);

    // ================= TITLE =================

    doc.setFontSize(16);
    doc.text(title, 14, 42);

    doc.setFontSize(10);
    doc.text(
        `Date: ${dayjs().format("DD/MM/YYYY HH:mm")}`,
        140,
        18
    );

    // ================= TABLE HEADER =================

    const headers = columns.map((c) => c.header);

    // ================= TABLE BODY =================

    const body = data.map((row, index) =>
        columns.map((col) => {
            if (col.key === "__index") return index + 1;
            return row[col.key] as string | number;
        })
    );

    // ================= TABLE =================

    autoTable(doc, {
        startY: 50,
        head: [headers],
        body,

        styles: {
            fontSize: 10,
            cellPadding: 3,
        },

        headStyles: {
            fillColor: [52, 152, 219],
            textColor: 255,
            fontStyle: "bold",
        },

        alternateRowStyles: {
            fillColor: [245, 245, 245],
        },

        margin: {
            left: 14,
            right: 14,
        },

        // ✅ FIXED HERE
        didDrawPage: (dataArg) => {
            const pageCount = getPageCount(doc);

            doc.setFontSize(9);

            doc.text(
                `Page ${dataArg.pageNumber} / ${pageCount}`,
                170,
                290
            );
        },
    });

    // ================= FOOTER =================

    const finalY = doc.lastAutoTable?.finalY ?? 60;

    doc.setFontSize(10);
    doc.text("Generated by System", 14, finalY + 10);

    // ================= FILE NAME =================

    const name =
        fileName ??
        `${type}-${dayjs().format("YYYYMMDD-HHmm")}`;

    doc.save(`${name}.pdf`);
};